apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-development
spec:
  selector:
    matchLabels:
      app: web-app
      environment: testing
  template:
    metadata:
      labels:
        app: web-app
        environment: testing
    spec:
      containers:
        - name: webapi1
          image: 720488407518.dkr.ecr.eu-central-1.amazonaws.com/aims-eks-demo-repo:latest
          resources:
            limits:
              cpu: "200m"
              memory: "500Mi"
          ports:
            - containerPort: 80
        - name: webapi2
          image: 720488407518.dkr.ecr.eu-central-1.amazonaws.com/aims-eks-demo-repo-2:latest
          resources:
            limits:
              cpu: "200m"
              memory: "500Mi"
          ports:
            - containerPort: 81
---
apiVersion: v1
kind: Service
metadata:
  name: weba-app-service
spec:
  selector:
    app: web-app
  ports:
    - name: https
      protocol: TCP
      port: 8080
      targetPort: 80
    - name: https 
      protocol: TCP
      port: 8081
      targetPort: 81
  type: LoadBalancer