apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-development
spec:
  selector:
    matchLabels:
      app: web-app
      environment: testing
  template:
    metadata:
      labels:
        app: web-app
        environment: testing
    spec:
      containers:
        - name: webapi1
          image: 720488407518.dkr.ecr.eu-central-1.amazonaws.com/aims-eks-demo-repo:latest
          resources:
            limits:
              cpu: "200m"
              memory: "500Mi"
          ports:
            - containerPort: 80
        - name: webapi2
          image: 720488407518.dkr.ecr.eu-central-1.amazonaws.com/aims-eks-demo-repo-2:latest
          resources:
            limits:
              cpu: "200m"
              memory: "500Mi"
          ports:
            - containerPort: 81
          env:
            - name: ASPNETCORE_URLS
              value: http://+:81
---
apiVersion: v1
kind: Service
metadata:
  name: web-app1-service
spec:
  selector:
    app: web-app
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-app2-service
spec:
  selector:
    app: web-app
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 81

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: api1-ingress
spec:
    rules:
    - http:
        paths:
        - path: /webapp1api
          pathType: Prefix
          backend:
            service:
              name: web-app1-service
              port:
                number: 80
        - path: /webapp2api
          pathType: Prefix
          backend:
            service:
              name: web-app2-service
              port:
                number: 81
